# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29710721d66b539b84598b40cf03d444a062e7a00a745bf53fd7fcd2271f412d2d55d08858ef9e6ecc8f366480387138967f48557fae73ebe8f4664f423d2e6

test:
  secret_key_base: 5c3d56a7d1535918ed9e984560674ec2650d91866963ad4d74513a4983e50ef68eb8454f9699cadc051576056b59d3339a99342aa1f8427c3af34c5b86ecba7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
